### ISSUE TITLE
Po co aż tyle odgałęzień?

### ISSUE THREAD

**Issue by Dorion300** [CodersCommunity/czatrepajr#14]
Po co aż tyle odgałęzień?

development
gh-pages
magic
master

Dwa nie wystarczą?
Jeden główny który został przetestowany i wydany.
A drugi testowy w fazie "produkcji".

**Comment by Comandeer** [comment]
Również zmieniłbym system commitów, bo nie sądzę, żeby tak częste PR były potrzebne.
