### ISSUE TITLE
Włączenie i Wyłączanie Czatrepajr

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/czatrepajr#24]
Wytyczne dla chłopaków od kodu :dancer:  :dancers:  
PR #23 

![zrzut ekranu z 2015-08-25 18 19 29](https://cloud.githubusercontent.com/assets/13868237/9472473/d9e4f8b6-4b55-11e5-8883-a41de8e6c175.png)

1. Po kliknięciu na przycisk wyłącz: (Identyfikator buttona: [min-chat-switch](https://github.com/CodersCommunity/czatrepajr/blame/feature_onoff/README.md#L41)  ) 
2. chat.stop dostaje true ( zatrzymuje się komunikacja i wysyłanie requestow )
3. do div o identyfikatorze [min-chat-content](https://github.com/CodersCommunity/czatrepajr/blame/feature_onoff/README.md#L43) zostaje dołączona klasa [.min-chat__content--collapsed](https://github.com/CodersCommunity/czatrepajr/blob/feature_onoff/style/main.css#L40)
4. Zmienia się napis Wyłącz na Włącz.

Opcja włączenia będzie podobna ;-)

ping @magic96 @marcinlacina

**Comment by Comandeer** [comment]
Nie .min-chat__content__collapsed ino .min-chat__content--collapsed, bo nie dodajemy elementu, a modyfikujemy już istniejący.
