### ISSUE TITLE
Kolejne usprawnienia chatu i naprawa błędów

### ISSUE THREAD

**Issue by efiku** [CodersCommunity/czatrepajr#27]
TODO:
- [x] Naprawić parsowanie wiadomości w message.js -> innerText
- [x] uzupełnianie nicków w momencie gdy pisząc na chacie @[Com]... i wciskając tab, to elegancko uzupełnia się nick na @Comandeer bez [ ] , bo pinguje do jakiegoś typa.
- [x] odseparować kod html gdzieś tutaj do repozytorium, niech pobiera z niego skrypt inicjujący tak samo jak pliki js itd.

**Comment by efiku** [comment]
Zrobiłem update , todo :)

**Comment by magic96** [comment]
:+1: Tylko pytanie, skąd weźmiesz bazę nicków? Zrobisz jakieś API z serwera, czy brać z historii wiadomości?

**Comment by efiku** [comment]
Z historii wiadomości, już wystarczająco męczymy serwer :+1:

**Comment by Comandeer** [comment]
> Firefox jak zwykle ma swoje "ja" i nie parsuje dobrze wiadomości na chacie ;-)

Bo robi to zgodnie ze standardami? :P Inna rzecz, że textContent w porównaniu do innerText ssie tak głośno, że słychać w pokoju obok…
