### ISSUE TITLE
Nie wyświetla nazwy użytkownika

### ISSUE THREAD

**Issue by event15** [CodersCommunity/czatrepajr#28]
Firefox 40.0.3
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
![przechwycenie obrazu ekranu_2015-09-21_12-46-56](https://cloud.githubusercontent.com/assets/9111118/9990117/df8a4cd0-605e-11e5-83d9-7b19b0072bfa.png)

**Comment by Comandeer** [comment]
Znany błąd - Firefox nie obsługuje HTMLElement.prototype.innerText

Już jest omówione w #27
